config/routes.rb
Rails.application.routes.draw do
	get 'ver_mas/:url', :to => 'personas#ver_mas', :as => 'ver_mas'
  resources :personas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/persona.rb
require 'httparty'

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    headers = { 
      "count" => "87",
      "next" => "https://swapi.co/api/people/?page=2",
      "previous" => "null"
    }
    @personas = HTTParty.get("https://swapi.co/api/people/", :headers => headers).parsed_response
    respond_to do |format|
      format.json {render :json => JSON.parse(@personas) }
      format.html {render :index}
    end
  end

  def ver_mas
    uri = "https://swapi.co/api/people/" + params[:url]
    @personas = HTTParty.get(uri).parsed_response
    respond_to do |format|
      format.json {render :json => JSON.parse(@personas) }
      format.html {render :ver_mas}
    end
  end
  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:name, :height, :mass, :hair_color, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/personas/_form.html.erb
<%= form_for(persona) do |f| %>
  <% if persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :height %>
    <%= f.text_field :height %>
  </div>

  <div class="field">
    <%= f.label :mass %>
    <%= f.number_field :mass %>
  </div>

  <div class="field">
    <%= f.label :hair_color %>
    <%= f.text_field :hair_color %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Personas</h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Height</th>
          <th>Mass</th>
          <th>Hair Color</th>
          <th>Operación</th>
        </tr>
      </thead>
      <tbody>
        <% @num = 0 %>
        <% @nume = 1 %>
        <% @personas.each do |evento| %>
          <% if @num > 1 %>
            <% if !evento[1].nil? %>
              <% evento[1].each do |e| %>
              <tr>
                <td><%= e['name'] %></td>
                <td><%= e['height'] %></td>
                <td><%= e['mass'] %></td>
                <td><%= e['hair_color'] %></td>
                <td><%= link_to "Ver más", ver_mas_path(@nume) %></td>
              </tr>
              <% @nume +=1 %>
              <% end %>
            <% end %>
          <% end %>
          <% @num += 1 %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

app/views/personas/new.html.erb
<h1>New Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @persona.name %>
</p>

<p>
  <strong>Height:</strong>
  <%= @persona.height %>
</p>

<p>
  <strong>Mass:</strong>
  <%= @persona.mass %>
</p>

<p>
  <strong>Hair color:</strong>
  <%= @persona.hair_color %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>

app/views/personas/ver_mas.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Personas</h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Height</th>
          <th>Mass</th>
          <th>Hair Color</th>
          <th>Skin Color</th>
          <th>Eye Color</th>
          <th>Birth Year</th>
          <th>Gender</th>
          <th>Homeworld</th>
          <th>Films</th>
          <th>Species</th>
          <th>Vehicles</th>
          <th>Starships</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @personas['name'] %></td>
          <td><%= @personas['height'] %></td>
          <td><%= @personas['mass'] %></td>
          <td><%= @personas['hair_color'] %></td>
          <td><%= @personas['skin_color'] %></td>
          <td><%= @personas['eye_color'] %></td>
          <td><%= @personas['birth_year'] %></td>
          <td><%= @personas['gender'] %></td>
          <td><%= @personas['homeworld'] %></td>
          <td><%= @personas['films'] %></td>
          <td><%= @personas['species'] %></td>
          <td><%= @personas['vehicles'] %></td>
          <td><%= @personas['starships'] %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <h3><%= link_to "Atrás", personas_path %></h3>
  </div>
</div>
<br>